language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
git:
  depth: 3
  quiet: true
rust:
- nightly
- beta
- stable
- 1.33.0
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache:
- cargo
- ccache
before_install: set -e
install:
- source ci/install_squash.sh
after_install: set +e
env:
  global:
  - secure: qsr1X85JkwnpOuWtOLEQ+C/R8FOJIx2mHnyqjJHU4+RgQEqAg3JjAu36z5VMkTDZupkdjfnB2bk7oYo6so4o5afsYaDlGbJXhTWvBVdLQcZXBGSQE+DwGhE2OUhEDQN2eFDwohme2r2nU1dVBq+GF9K26JSwrm2kW2dons53msjEUPuhEovRBk41z96hlOYl7mWJCFGA9QqFCfECFM1s59XiFOSk5rQlurSlOVkW+BKpNUFWwRum1EZ4PnV3YjfEDdVZmHMYC3O0c+IYwTQqydsoz7M+iVEdqOfhOzLgXX3TREKQJcLOdDpOmW/GNICp1QRd8nfX9bT29/Cq3Tm/yTl2/UrdhgQMXdufQoIwhhl3min3Bke30Libl+jFPtjxdudy5DdedrowxMLfHqhwkAGNOu9crTiw0y5+CYuXG84iW5r0S1ChEm7wR0j2jOj075rNyBAglwS3jBwHaJGz/4BWVOw2EpJyEgq7EKL/GDiLg7D3UTXyRElNwH15MgmrEkfa5tSwFovfdQztQxcknwo7PMwteZIOcvLu+G3KHBuRNQRi6xoIzc67d4VJxSfUnkTF1tBf5QM5Ikw71pM+Hga1anC03Xi+HW/VhuCyvjQ4X6hJwEUei5B4MzOwf6lrAr5fX2h+s3gInXqxMKcdwgcbeXJ4QI5bY6zfOiXNf9M=
