dist: trusty
sudo: false
language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
rust:
- nightly
- beta
- stable
- 1.17.0
cache:
- cargo
- ccache
before_install: set -e
install:
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
- source ci/install_squash.sh
- source ~/.cargo/env || true
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo --only stable doc
after_script: set +e
before_cache:
- chmod -R a+r $HOME/.cargo
after_success:
- travis-cargo --only stable doc-upload
- travis-cargo coveralls --no-sudo --verify
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
  - secure: qsr1X85JkwnpOuWtOLEQ+C/R8FOJIx2mHnyqjJHU4+RgQEqAg3JjAu36z5VMkTDZupkdjfnB2bk7oYo6so4o5afsYaDlGbJXhTWvBVdLQcZXBGSQE+DwGhE2OUhEDQN2eFDwohme2r2nU1dVBq+GF9K26JSwrm2kW2dons53msjEUPuhEovRBk41z96hlOYl7mWJCFGA9QqFCfECFM1s59XiFOSk5rQlurSlOVkW+BKpNUFWwRum1EZ4PnV3YjfEDdVZmHMYC3O0c+IYwTQqydsoz7M+iVEdqOfhOzLgXX3TREKQJcLOdDpOmW/GNICp1QRd8nfX9bT29/Cq3Tm/yTl2/UrdhgQMXdufQoIwhhl3min3Bke30Libl+jFPtjxdudy5DdedrowxMLfHqhwkAGNOu9crTiw0y5+CYuXG84iW5r0S1ChEm7wR0j2jOj075rNyBAglwS3jBwHaJGz/4BWVOw2EpJyEgq7EKL/GDiLg7D3UTXyRElNwH15MgmrEkfa5tSwFovfdQztQxcknwo7PMwteZIOcvLu+G3KHBuRNQRi6xoIzc67d4VJxSfUnkTF1tBf5QM5Ikw71pM+Hga1anC03Xi+HW/VhuCyvjQ4X6hJwEUei5B4MzOwf6lrAr5fX2h+s3gInXqxMKcdwgcbeXJ4QI5bY6zfOiXNf9M=
